export const tbodyCommandTypes = {
  MAKE_TBODY: "MAKE_TBODY",
  TBODY_ASCDESC: "TBODY_ASCDESC",
  ORDER_VALUE: "ORDER_VALUE",
  ISINFAV_VALUE: "ISINFAV_VALUE",
  SUGG_VALUE: "SUGG_VALUE",
  TSEARCH_VALUE: "TSEARCH_VALUE",
  UPDATETRIGGER_VALUE: "UPDATETRIGGER_VALUE",
  HINT_SUGG_VALUE: "HINT_SUGG_VALUE"
};
